# Generated by Django 5.2.4 on 2025-07-31 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('category', models.CharField(choices=[('health', 'Health'), ('work', 'Work'), ('learning', 'Learning')], max_length=20)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HabitCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('mood', models.CharField(blank=True, max_length=10)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='habits.habit')),
            ],
        ),
    ]
